# Generated by Django 5.2.17 on 2026-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_normalized',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('active', 'Active'), ('suspended', 'Suspended')], default='unverified', max_length=20),
        ),
    ]
