# Generated by Django 5.2.17 on 2026-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_normalized', models.CharField(editable=False, max_length=255, unique=True)),
                ('industry_tag', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
    ]
